name: Export Manual

on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: "Godot version (without v prefix)"
        default: 4.1.1

jobs:
  export_game:
    runs-on: ubuntu-latest

    permissions: write-all

    name: Export Game
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Export Game
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ github.event.inputs.godot_version }}/Godot_v${{ github.event.inputs.godot_version }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ github.event.inputs.godot_version }}/Godot_v${{ github.event.inputs.godot_version }}-stable_export_templates.tpz
          relative_project_path: ./project
          cache: true
          archive_output: true

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
