name: Release

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.1.1
  RELEASE_ITCH: true

jobs:
  release_game:
    runs-on: ubuntu-latest

    permissions: write-all

    name: Release Game
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          release-type: simple
          extra-files: |
            project/version.gd

      - name: Set up butler
        if: ${{ steps.release.outputs.release_created }}
        uses: jdno/setup-butler@v1

      - name: Export Game
        if: ${{ steps.release.outputs.release_created }}
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          relative_project_path: ./project
          cache: true
          archive_output: true

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for FILE_PATH in ${{ steps.export.outputs.archive_directory }}/*; do
            gh release upload ${{ steps.release.outputs.tag_name }} "$FILE_PATH" --clobber
          done

      - name: Deploy to Itch.io
        if: ${{ steps.release.outputs.release_created }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          BUILD_VERSION: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
        run: |
          for FILE_PATH in ${{ steps.export.outputs.archive_directory }}/*; do
            directory=$FILE_PATH
            filename=$(basename "$FILE_PATH")
            platform="${filename%%.*}"
            version="${{ steps.release.outputs.tag_name }}"
            version="${version#v}" # Remove the "v" prefix
            user=${{ vars.ITCH_USERNAME }}
            game=${{ vars.ITCH_GAME_ID }}
            channel=${platform}
            butler push "$directory" "$user"/"$game":"$channel" --userversion "$version"
          done
