name: release

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: godot-game-template-extended
  EXPORT_FOLDER: export
  RELEASE_ITCH: true
  RELEASE_WEB: true
  RELEASE_WINDOWS: true
  RELEASE_LINUX: true
  RELEASE_MACOS: true

permissions:
  contents: write
  pull-requests: write

jobs:
  export:
    name: Export

    runs-on: ubuntu-20.04

    container:
      image: barichello/godot-ci:4.1.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Godot build environment
        run: |
          mkdir -v -p $EXPORT_FOLDER/windows $EXPORT_FOLDER/linux $EXPORT_FOLDER/web $EXPORT_FOLDER/mac ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Web Build
        if: ${{ env.RELEASE_WEB=='true' }}
        run: godot -v --path ./project --export-release --headless "HTML5" ./$EXPORT_FOLDER/web/index.html

      - name: Windows Build
        if: ${{ env.RELEASE_WINDOWS=='true' }}
        run: godot -v --path ./project --export-release --headless "Windows Desktop" ./$EXPORT_FOLDER/windows/$EXPORT_NAME.exe

      - name: Linux Build
        if: ${{ env.RELEASE_LINUX=='true' }}
        run: godot -v --path ./project --export-release --headless "Linux/X11" ./$EXPORT_FOLDER/linux/$EXPORT_NAME.x86_64

      - name: Mac Build
        if: ${{ env.RELEASE_MACOS=='true' }}
        run: godot -v --path ./project --export-release --headless "Mac OSX" ./$EXPORT_FOLDER/mac/$EXPORT_NAME.zip

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: $EXPORT_FOLDER/web
          retention-days: 1

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: $EXPORT_FOLDER/windows
          retention-days: 1

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: $EXPORT_FOLDER/linux
          retention-days: 1

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac
          path: $EXPORT_FOLDER/mac
          retention-days: 1

      - name: Zip Folder - Web
        run: zip -r itch_web.zip $EXPORT_FOLDER/web

      - name: Zip Folder - Windows
        run: zip -r itch_windows.zip $EXPORT_FOLDER/windows

      - name: Zip Folder - Linux
        run: zip -r itch_linux.zip $EXPORT_FOLDER/linux

      - name: Zip Folder - Mac
        run: zip -r itch_mac.zip $EXPORT_FOLDER/mac

      - name: Deploy to itch.io - Web
        if: ${{ env.RELEASE_ITCH=='true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch_web.zip

      - name: Deploy to itch.io - Windows
        if: ${{ env.RELEASE_ITCH=='true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch_windows.zip

      - name: Deploy to itch.io - Linux
        if: ${{ env.RELEASE_ITCH=='true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch_linux.zip

      - name: Deploy to itch.io - Mac
        if: ${{ env.RELEASE_ITCH=='true' }}
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: mac
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: itch_mac.zip

      - name: Release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          release-type: simple
          package-name: godot-game-template-extended
          extra-files: |
            project/version.gd
